### PR TITLE
Add support for RwLock

### LINKED ISSUE #21: Add support for RwLock
I notice that `loom::sync` has a [mock implementation of `std::sync::Mutex`](https://github.com/carllerche/loom/blob/master/src/sync/mutex.rs) but lacks a mock `std::sync::RwLock`. It would be nice to be able to test code using read-write locks with `loom`.

### PR DESCRIPTION
**Pull request by hawkw**
Fixes #21

This branch adds support for mock `RwLock`s. This PR is the same as PR
#88, but updated to build against the current master. All credit is due
to @pop.

### CODE REVIEW

**Comment by hawkw** [comment]
@pop, if you'd prefer to merge your PR rather than this one, I can open a PR against your fork to merge my changes to your branch?

**Comment by pop** [comment]
Oh cool! I wasn't sure if my PR was ready to be merged yet.

If it's all the same to you let's merge into my PR and them merge that into master. 😃

**Comment by hawkw** [comment]
@pop sounds good, will do! I think we still need an approval from @carllerche.

**Comment by carllerche** [comment]
Closed by #88

**Pull request closed without merging**
