### PR TITLE
Update generator to 0.8.1

### PR DESCRIPTION
**Pull request by fornwall**
Closes: #337

### CODE REVIEW

**Comment by fornwall** [comment]
The minimal dependency versions check is failing due to `generator` static `libc` version `0.2` as the minimal version, but does not actually build against a libc version that old.

Proposed bumping that for `generator` here: https://github.com/Xudong-Huang/generator-rs/pull/57

**Comment by fornwall** [comment]
> Proposed bumping that for generator here: https://github.com/Xudong-Huang/generator-rs/pull/57

This has now been merged and released as `generator` version `0.8.1`. I've bumped to that, and this PR should now be ready.

**Review by taiki-e — APPROVED** [review]
Thanks!

**Comment by torokati44** [comment]
It would be nice to get a new release with this in. Not important, just to help clean up some transitive dependency version duplications of downstream projects. :innocent:

**Comment by Darksonn** [comment]
Done in #348.

**Comment by torokati44** [comment]
Thank you! ☺️

**Pull request merged**
